// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/chat-with-yaro.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var chat_with_yaro_default = defineTool({
  name: "chat_with_yaro",
  title: "Chat with Yaro (AI therapist)",
  description: "Send a message to WellMindAI's Yaro \u2014 a compassionate multilingual (Hindi/English/Hinglish/Tamil/Bengali/Spanish) AI therapist trained on DSM-5, ICD-11, PHQ-9, GAD-7, PCL-5. Returns Yaro's reply plus a real-time clinical pattern read (PHQ-9/GAD-7 bands, DSM hints, crisis flag).",
  inputSchema: {
    message: z.string().min(1).describe("The user's message to Yaro."),
    language: z.enum(["auto", "en", "hi", "hinglish", "ta", "bn", "es"]).optional().describe("Language hint. 'auto' mirrors the user's language."),
    history: z.array(
      z.object({
        sender: z.enum(["user", "ai"]),
        content: z.string()
      })
    ).optional().describe("Recent conversation turns for context.")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ message, language, history }) => {
    const url = "https://tcqwhsdhbxlzxuoekjom.supabase.co/functions/v1/ai-counselor";
    const anon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcXdoc2RoYnhsenh1b2Vram9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTAwNzEsImV4cCI6MjA2OTIyNjA3MX0.lB1_VKY_eUKJfhRX1tZggll5O-md1NB-WpL9wUg4p64";
    const lang = language ?? "auto";
    const hint = lang === "auto" ? "Mirror the user's language exactly." : `Respond primarily in ${lang}.`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${anon}`,
        apikey: anon
      },
      body: JSON.stringify({
        message: `${message}

[LANG_HINT: ${hint}]`,
        counselorId: "yaro",
        conversationHistory: (history ?? []).slice(-12)
      })
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return {
        content: [{ type: "text", text: `Yaro engine error ${res.status}: ${text}` }],
        isError: true
      };
    }
    const data = await res.json();
    const reply = data?.response || data?.message || "";
    return {
      content: [{ type: "text", text: String(reply) }],
      structuredContent: {
        reply,
        clinical: data?.clinical ?? null,
        provider: data?.provider,
        model: data?.model,
        degraded: Boolean(data?.degraded)
      }
    };
  }
});

// src/lib/mcp/tools/clinical-screen.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var clinical_screen_default = defineTool2({
  name: "clinical_screen",
  title: "Run a clinical screener",
  description: "Score a PHQ-9 (depression), GAD-7 (anxiety) or PCL-5 (PTSD) screener from item responses (0-3 per item; PCL-5 0-4). Returns total score, severity band, and safe next-step guidance. Not a diagnosis.",
  inputSchema: {
    instrument: z2.enum(["phq9", "gad7", "pcl5"]),
    answers: z2.array(z2.number().int().min(0).max(4)).describe("Item answers in order. PHQ-9: 9 items 0-3. GAD-7: 7 items 0-3. PCL-5: 20 items 0-4.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ instrument, answers }) => {
    const sum = answers.reduce((a, b) => a + b, 0);
    let band = "n/a";
    let expected = 0;
    if (instrument === "phq9") {
      expected = 9;
      band = sum <= 4 ? "minimal" : sum <= 9 ? "mild" : sum <= 14 ? "moderate" : sum <= 19 ? "moderately severe" : "severe";
    } else if (instrument === "gad7") {
      expected = 7;
      band = sum <= 4 ? "minimal" : sum <= 9 ? "mild" : sum <= 14 ? "moderate" : "severe";
    } else {
      expected = 20;
      band = sum >= 33 ? "probable PTSD" : "sub-threshold";
    }
    const warn = answers.length !== expected ? `Warning: expected ${expected} items, got ${answers.length}.` : "";
    const text = `${instrument.toUpperCase()} score: ${sum} (${band}). ${warn}
This is a screening signal, not a diagnosis. If crisis: iCall 9152987821 (India).`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { instrument, score: sum, band }
    };
  }
});

// src/lib/mcp/tools/crisis-resources.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var RESOURCES = {
  IN: [
    { name: "iCall", phone: "9152987821", hours: "Mon-Sat 8am-10pm" },
    { name: "Vandrevala Foundation", phone: "1860-2662-345", hours: "24/7" },
    { name: "AASRA", phone: "9820466726", hours: "24/7" }
  ],
  US: [
    { name: "988 Suicide & Crisis Lifeline", phone: "988", hours: "24/7" },
    { name: "Crisis Text Line", phone: "Text HOME to 741741", hours: "24/7" }
  ],
  GB: [{ name: "Samaritans", phone: "116 123", hours: "24/7" }],
  DEFAULT: [{ name: "Befrienders Worldwide", phone: "befrienders.org", hours: "Directory" }]
};
var crisis_resources_default = defineTool3({
  name: "crisis_resources",
  title: "Get crisis helplines",
  description: "Return verified mental-health crisis helplines for a country (ISO-2). Falls back to an international directory.",
  inputSchema: {
    country: z3.string().length(2).optional().describe("ISO-2 country code, e.g. IN, US, GB")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ country }) => {
    const key = (country ?? "").toUpperCase();
    const list = RESOURCES[key] ?? RESOURCES.DEFAULT;
    const text = list.map((r) => `\u2022 ${r.name} \u2014 ${r.phone} (${r.hours})`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { country: key || "DEFAULT", resources: list }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "wellmindai-mcp",
  title: "WellMindAI MCP",
  version: "0.1.0",
  instructions: "Tools for WellMindAI \u2014 chat with Yaro (multilingual AI therapist trained on DSM-5/ICD-11/PHQ-9/GAD-7/PCL-5), score standard clinical screeners, and fetch crisis helplines. Use `chat_with_yaro` for open conversation, `clinical_screen` for scoring, `crisis_resources` for safety.",
  tools: [chat_with_yaro_default, clinical_screen_default, crisis_resources_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
