// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcqwhsdhbxlzxuoekjom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcXdoc2RoYnhsenh1b2Vram9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTAwNzEsImV4cCI6MjA2OTIyNjA3MX0.lB1_VKY_eUKJfhRX1tZggll5O-md1NB-WpL9wUg4p64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});